### ISSUE TITLE
fibonacci fib word

### ISSUE THREAD

**Issue by zuloloxi** [Howerd/colorForth#2]
Hello

How I coud insert (with colors) in colorforth cf2019 version 2021 aug 15, a fibonacci word from disccution : 
http://www.strangegizmo.com/forth/ColorForth/msg00809.html or http://www.strangegizmo.com/forth/ColorForth/msg00022.html
```
: fib push 1 dup pop -2 +
: f -if drop nip ; then push swap over + pop -1 + f ;
```
Thanks,

**Comment by Howerd** [comment]
Hi Zuloloxi,

1. after starting cf2019 with "go.bat" press the space bar to exit the editor.
2. type _250_edit_    on the keypad where '_' represents the space bar
3. press the 'r' key on the keypad - the keypad should now be red
4. type  fib_    on the keypad, the keypad should now be green
5. press the F4 key on the keyboard - the screen will now show the ":" in colour-blind mode
6. continue typing the rest of the definition of "fib" 
7. press . on the keypad then press r to select red token colour again, press f_
8. continue typing the rest of the definition of "f"
9. press . to get back to the main edit screen
10. press _   (the space bar) to leave the editor
11. type  sa_  (short for save and return to the editor)
12. press _ to leave the editor again 
13. type ll_ to load the current screen
14. type a number, then f_ to run the program.

I know there is a lot to learn, and it is very different to a normal text file editor.

Let me know how it goes :-)

Howerd

**Comment by Howerd** [comment]
Hi zuloloxi,

I have just added a new file "How_to_program_in_colorForth_cf2019.pdf"
also available from my website here : https://www.inventio.co.uk/colorforth/
https://www.inventio.co.uk/colorforth/How_to_program_in_colorForth_cf2019.pdf

I hope that this explains things more clearly :-)

Cheers,
Howerd

**Comment by zuloloxi** [comment]
A Happy New Year 2022 !
Many Thanks for helping.
I could insert in cf2019 the fib word, it calculate, but the returned number it is not like in Fibonacci sequence [here](https://en.wikipedia.org/wiki/Fibonacci_number)

> 0 fib --> result 1 must be 0
> 1 fib --> result 1 must be 1
> 2 fib --> result 2 must be 1
> 3 fib --> result 3 must be 2
> 4 fib --> result 5 must be 3
> 5 fib --> result 8 must be 5
> 6 fib --> result 13 must be 8
 ...
It it possible to debug in cf2019 ?

best regards,

PS
I modified the fib and f, it seems working  :

> : fib push 0 1 pop -2 +
> : f -if 1 + -if drop drop ; then drop nip ; then push swap over + pop -1 + f ;
