### ISSUE TITLE
"2drop" incorrectly encoded in "ForthNamesROM" asm data

### ISSUE THREAD

**Issue by marco-nicola** [Howerd/colorForth#4]
Hi,

I think there is an error regarding the Shannon-Fano encoding of the word `2drop` (i.e. `two_drop_`), in the data defined under `ForthNamesROM` from the assembly code.

Here's the affected line of code:

```asm
    dd 0xD5833620   ; 2drop     two_drop_
```

Among others, see line `6584` from `cf2019.nasm`.

That should be the encoding for `2dup`, which incidentally is defined on the line right above.

I believe the correct encoding for `2drop` should be `0xD5804F10`.

I could notice the problem in nasm source files, and PDF listings, from versions `cf2019` and `cf2022_Issue_2022Apr08`. While I didn't look at the content from other archives, I suspect it might affect all versions.

I hope I got this right!

Thanks for the amazing work :heart:

**Comment by Howerd** [comment]
Hi Marco,

Thanks :-)
I will take a look - sorry it has taken me so long to notice your message! Holidays and all...

Cheers,
Howerd

**Comment by Howerd** [comment]
Hi Marco,

I've just checked - you are right, and your fix is right too :-)
The error actually broke 2dup too... Time to add the Hayes test suite I think...

I will update GitHub etc ASAP.

Thanks again :-)

Cheers,
Howerd
